### ISSUE TITLE
Default font definition fails in IE9

### ISSUE THREAD

**Issue by Chris-May** [PunchRVA/starterfiles#10]
From `starterfiles/htdocs/assets/scss/global-partials/_typography.scss:4`: Using `rem-calc()` to define default `font` makes this un-usable for IE9.

Maybe(?) we should have a fallback commented out for when we need to support IE9?

OR

Is a `rem` needed at this point, since it's applying to `<body>`... possibly since I _think_ font is being inherited through the cascade?

**Comment by philbarbato** [comment]
We should be able to use `em

**Comment by philbarbato** [comment]
So, the `$body-font-size` and `$body-line-height` variables are not just used on the body element. They're used to maintain a standard size we can use directly or multiplied/divided in some way. I use `$body-line-height` to set vertical margins and padding and even heights of some items as well. This is my ongoing effort to maintain some kind of vertical rhythm.

By keeping the variable in rems, we can change font sizes globally and maintain the relative sizes of everything.

I think a REM polyfill wrapped in an IE conditional is what's called-for here.
