### ISSUE TITLE
Add Sublime Text config file.

### ISSUE THREAD

**Issue by philbarbato** [PunchRVA/starterfiles#9]
This will be mostly helpful with new people, but will help keep us all in line.

**Comment by Chris-May** [comment]
I forget what we talked about here.
Is this a .sublime-project file with project-level configurations in it?

**Comment by philbarbato** [comment]
Yeah. I don't know if this is necessary.

**Comment by Chris-May** [comment]
Necessary? Maybe not, but possibly helpful. I'll add one and we'll see if it sticks.
